development:
  adapter: mysql
  database: mbra_development
  username: mbra_development
  host: localhost
  encoding: utf8

test:
  adapter: mysql
  database: mrba_test
  username: mbra_test
  host: localhost
  encoding: utf8

production:
  adapter: mysql
  database: racing_on_rails_production
  username: root
  encoding: utf8
  host: localhost
