development:
  adapter: mysql
  database: mbra_development
  username: mbra_development
  host: localhost
  encoding: utf8

test:
  adapter: mysql
  database: mbra_test
  username: mbra_test
  password:
  host: localhost
  encoding: utf8

staging:
  adapter: mysql
  database: albert_staging
  username: albert_staging
  password: 5bM1wfrfE7
  encoding: utf8
  socket: /tmp/mysql.sock

production:
  adapter: mysql
  database: racing_on_rails_production
  username: root
  encoding: utf8
  host: localhost
